In [17]:

import numpy as np

In [18]:
#2d array
array_2d = np.array([[1, 2, 3],[4, 5, 6]])
print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


In [19]:
#3d array
array_3d = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print("\n3D Array:")
print(array_3d)


3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:

#np.arange(0, 10, 2)
 np.arange((3, 4))

IndentationError: unexpected indent (3997563774.py, line 2)

In [ ]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

y = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]]) 

print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.percentile(a, 50))  #median
print(np.percentile(a, 25))  #1st quartile
print(np.percentile(a, 75))  #3rd quartile

5.0
3.0
7.0


In [ ]:
f